//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 8/13/2020 1:44:38 PM
namespace Mod.Framework.Max.WebDataServices
{
    
    /// <summary>
    /// There are no comments for MaxUserAndGroupEntities in the schema.
    /// </summary>
    public partial class MaxUserAndGroupEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new MaxUserAndGroupEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MaxUserAndGroupEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for USERS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<USER> USERS
        {
            get
            {
                if ((this._USERS == null))
                {
                    this._USERS = base.CreateQuery<USER>("USERS");
                }
                return this._USERS;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<USER> _USERS;
        /// <summary>
        /// There are no comments for GROUPS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<GROUP> GROUPS
        {
            get
            {
                if ((this._GROUPS == null))
                {
                    this._GROUPS = base.CreateQuery<GROUP>("GROUPS");
                }
                return this._GROUPS;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<GROUP> _GROUPS;
        /// <summary>
        /// There are no comments for USERS_TO_GROUPS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<USER_TO_GROUP> USERS_TO_GROUPS
        {
            get
            {
                if ((this._USERS_TO_GROUPS == null))
                {
                    this._USERS_TO_GROUPS = base.CreateQuery<USER_TO_GROUP>("USERS_TO_GROUPS");
                }
                return this._USERS_TO_GROUPS;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<USER_TO_GROUP> _USERS_TO_GROUPS;
        /// <summary>
        /// There are no comments for USER_TABLEAU_SITES in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<USER_TABLEAU_SITES> USER_TABLEAU_SITES
        {
            get
            {
                if ((this._USER_TABLEAU_SITES == null))
                {
                    this._USER_TABLEAU_SITES = base.CreateQuery<USER_TABLEAU_SITES>("USER_TABLEAU_SITES");
                }
                return this._USER_TABLEAU_SITES;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<USER_TABLEAU_SITES> _USER_TABLEAU_SITES;
        /// <summary>
        /// There are no comments for AGENCIES in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AGENCY> AGENCIES
        {
            get
            {
                if ((this._AGENCIES == null))
                {
                    this._AGENCIES = base.CreateQuery<AGENCY>("AGENCIES");
                }
                return this._AGENCIES;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AGENCY> _AGENCIES;
        /// <summary>
        /// There are no comments for BUREAUS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<BUREAU> BUREAUS
        {
            get
            {
                if ((this._BUREAUS == null))
                {
                    this._BUREAUS = base.CreateQuery<BUREAU>("BUREAUS");
                }
                return this._BUREAUS;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<BUREAU> _BUREAUS;
        /// <summary>
        /// There are no comments for USERS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUSERS(USER uSER)
        {
            base.AddObject("USERS", uSER);
        }
        /// <summary>
        /// There are no comments for GROUPS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGROUPS(GROUP gROUP)
        {
            base.AddObject("GROUPS", gROUP);
        }
        /// <summary>
        /// There are no comments for USERS_TO_GROUPS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUSERS_TO_GROUPS(USER_TO_GROUP uSER_TO_GROUP)
        {
            base.AddObject("USERS_TO_GROUPS", uSER_TO_GROUP);
        }
        /// <summary>
        /// There are no comments for USER_TABLEAU_SITES in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUSER_TABLEAU_SITES(USER_TABLEAU_SITES uSER_TABLEAU_SITES)
        {
            base.AddObject("USER_TABLEAU_SITES", uSER_TABLEAU_SITES);
        }
        /// <summary>
        /// There are no comments for AGENCIES in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAGENCIES(AGENCY aGENCY)
        {
            base.AddObject("AGENCIES", aGENCY);
        }
        /// <summary>
        /// There are no comments for BUREAUS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBUREAUS(BUREAU bUREAU)
        {
            base.AddObject("BUREAUS", bUREAU);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"MaxUserAndGroupModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11" +
                "/edm\"><EntityType Name=\"USER\"><Key><PropertyRef Name=\"MF_USERID\" /></Key><Proper" +
                "ty Name=\"MF_USERID\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"7\" FixedLength" +
                "=\"true\" Unicode=\"false\" /><Property Name=\"FIRST_NAME\" Type=\"Edm.String\" Nullable" +
                "=\"false\" MaxLength=\"30\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"MI" +
                "DDLE_NAME\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"30\" FixedLength=\"false\"" +
                " Unicode=\"false\" /><Property Name=\"LAST_NAME\" Type=\"Edm.String\" Nullable=\"false\"" +
                " MaxLength=\"30\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"PHONE\" Typ" +
                "e=\"Edm.String\" Nullable=\"false\" MaxLength=\"14\" FixedLength=\"false\" Unicode=\"fals" +
                "e\" /><Property Name=\"PHONE_EXT\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"5\"" +
                " FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"FAX\" Type=\"Edm.String\" Nu" +
                "llable=\"false\" MaxLength=\"14\" FixedLength=\"false\" Unicode=\"false\" /><Property Na" +
                "me=\"EMAIL\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"60\" FixedLength=\"false\"" +
                " Unicode=\"false\" /><Property Name=\"ADDRESS_1\" Type=\"Edm.String\" Nullable=\"false\"" +
                " MaxLength=\"35\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"ADDRESS_2\"" +
                " Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"35\" FixedLength=\"false\" Unicode=\"" +
                "false\" /><Property Name=\"CITY\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"20\"" +
                " FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"STATE\" Type=\"Edm.String\" " +
                "Nullable=\"false\" MaxLength=\"2\" FixedLength=\"false\" Unicode=\"false\" /><Property N" +
                "ame=\"ZIPCODE\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"9\" FixedLength=\"fals" +
                "e\" Unicode=\"false\" /><Property Name=\"USER_STATUS\" Type=\"Edm.String\" Nullable=\"fa" +
                "lse\" MaxLength=\"1\" FixedLength=\"true\" Unicode=\"false\" /><Property Name=\"USER_CLA" +
                "SSIFICATION\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" FixedLength=\"fals" +
                "e\" Unicode=\"false\" /><Property Name=\"UCASE_LAST_NAME\" Type=\"Edm.String\" MaxLengt" +
                "h=\"30\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"UCASE_FIRST_NAME\" T" +
                "ype=\"Edm.String\" MaxLength=\"30\" FixedLength=\"false\" Unicode=\"false\" /><Property " +
                "Name=\"UCASE_MIDDLE_NAME\" Type=\"Edm.String\" MaxLength=\"30\" FixedLength=\"false\" Un" +
                "icode=\"false\" /><Property Name=\"LDAP_EMAIL\" Type=\"Edm.String\" MaxLength=\"96\" Fix" +
                "edLength=\"false\" Unicode=\"false\" /><Property Name=\"SDATETIME\" Type=\"Edm.DateTime" +
                "\" Nullable=\"false\" Precision=\"6\" /><Property Name=\"ORGANIZATION\" Type=\"Edm.Strin" +
                "g\" MaxLength=\"250\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"COUNTRY" +
                "_CODE\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"2\" FixedLength=\"false\" Unic" +
                "ode=\"false\" /><Property Name=\"ORG_AGENCY\" Type=\"Edm.String\" MaxLength=\"3\" FixedL" +
                "ength=\"true\" Unicode=\"false\" /><Property Name=\"ORG_BUREAU\" Type=\"Edm.String\" Nul" +
                "lable=\"false\" MaxLength=\"2\" FixedLength=\"false\" Unicode=\"false\" /><Property Name" +
                "=\"AGEABRV\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"8\" FixedLength=\"false\" " +
                "Unicode=\"false\" /><Property Name=\"TEST_ACCT_ID\" Type=\"Edm.String\" Nullable=\"fals" +
                "e\" MaxLength=\"1\" FixedLength=\"true\" Unicode=\"false\" /><Property Name=\"ADMIN_ACCT" +
                "_ID\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"1\" FixedLength=\"true\" Unicode" +
                "=\"false\" /><NavigationProperty Name=\"USER_TO_USERS_TO_GROUPS\" Relationship=\"MaxU" +
                "serAndGroupModel.USERSUSERS_TO_GROUPS\" ToRole=\"USERS_TO_GROUPS\" FromRole=\"USERS\"" +
                " /></EntityType><EntityType Name=\"GROUP\"><Key><PropertyRef Name=\"COMMUNITY_GROUP" +
                "\" /></Key><Property Name=\"COMMUNITY_GROUP\" Type=\"Edm.String\" Nullable=\"false\" Ma" +
                "xLength=\"255\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"COMMUNITY_GR" +
                "OUPNAME\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"64\" FixedLength=\"true\" Un" +
                "icode=\"false\" /><NavigationProperty Name=\"GROUP_TO_USERS_TO_GROUPS\" Relationship" +
                "=\"MaxUserAndGroupModel.GROUPSUSERS_TO_GROUPS\" ToRole=\"USERS_TO_GROUPS\" FromRole=" +
                "\"GROUPS\" /></EntityType><EntityType Name=\"USER_TO_GROUP\"><Key><PropertyRef Name=" +
                "\"COMMUNITY_GROUP\" /><PropertyRef Name=\"MF_USERID\" /></Key><Property Name=\"MF_USE" +
                "RID\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"7\" FixedLength=\"true\" Unicode" +
                "=\"false\" /><Property Name=\"COMMUNITY_GROUP\" Type=\"Edm.String\" Nullable=\"false\" M" +
                "axLength=\"255\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"COMMUNITY_G" +
                "ROUPNAME\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"64\" FixedLength=\"true\" U" +
                "nicode=\"false\" /><NavigationProperty Name=\"USER\" Relationship=\"MaxUserAndGroupMo" +
                "del.USERSUSERS_TO_GROUPS\" ToRole=\"USERS\" FromRole=\"USERS_TO_GROUPS\" /><Navigatio" +
                "nProperty Name=\"GROUP\" Relationship=\"MaxUserAndGroupModel.GROUPSUSERS_TO_GROUPS\"" +
                " ToRole=\"GROUPS\" FromRole=\"USERS_TO_GROUPS\" /></EntityType><EntityType Name=\"USE" +
                "R_TABLEAU_SITES\"><Key><PropertyRef Name=\"COMMUNITY_GROUP\" /><PropertyRef Name=\"M" +
                "F_USERID\" /><PropertyRef Name=\"TABLEAU_SITE\" /></Key><Property Name=\"LDAP_EMAIL\"" +
                " Type=\"Edm.String\" MaxLength=\"96\" FixedLength=\"false\" Unicode=\"false\" /><Propert" +
                "y Name=\"MF_USERID\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"7\" FixedLength=" +
                "\"true\" Unicode=\"false\" /><Property Name=\"COMMUNITY_GROUP\" Type=\"Edm.String\" Null" +
                "able=\"false\" MaxLength=\"255\" FixedLength=\"false\" Unicode=\"false\" /><Property Nam" +
                "e=\"TABLEAU_SITE\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" FixedLength=" +
                "\"false\" Unicode=\"false\" /></EntityType><EntityType Name=\"AGENCY\"><Key><PropertyR" +
                "ef Name=\"ORG_AGENCY\" /></Key><Property Name=\"ORG_AGENCY\" Type=\"Edm.String\" Nulla" +
                "ble=\"false\" MaxLength=\"3\" FixedLength=\"true\" Unicode=\"false\" /><Property Name=\"A" +
                "GEAI\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"1\" FixedLength=\"true\" Unicod" +
                "e=\"false\" /><Property Name=\"AGEST\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=" +
                "\"30\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"AGETL\" Type=\"Edm.Stri" +
                "ng\" Nullable=\"false\" MaxLength=\"64\" FixedLength=\"false\" Unicode=\"false\" /><Prope" +
                "rty Name=\"AGELT\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"164\" FixedLength=" +
                "\"false\" Unicode=\"false\" /><Property Name=\"AGEABRV\" Type=\"Edm.String\" Nullable=\"f" +
                "alse\" MaxLength=\"8\" FixedLength=\"false\" Unicode=\"false\" /></EntityType><EntityTy" +
                "pe Name=\"BUREAU\"><Key><PropertyRef Name=\"ORG_AGENCY\" /><PropertyRef Name=\"ORG_BU" +
                "REAU\" /></Key><Property Name=\"ORG_AGENCY\" Type=\"Edm.String\" Nullable=\"false\" Max" +
                "Length=\"3\" FixedLength=\"true\" Unicode=\"false\" /><Property Name=\"ORG_BUREAU\" Type" +
                "=\"Edm.String\" Nullable=\"false\" MaxLength=\"2\" FixedLength=\"false\" Unicode=\"false\"" +
                " /><Property Name=\"BURSEQ\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"2\" Fixe" +
                "dLength=\"false\" Unicode=\"false\" /><Property Name=\"BURAI\" Type=\"Edm.String\" Nulla" +
                "ble=\"false\" MaxLength=\"1\" FixedLength=\"true\" Unicode=\"false\" /><Property Name=\"B" +
                "URST\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"30\" FixedLength=\"false\" Unic" +
                "ode=\"false\" /><Property Name=\"BURTL\" Type=\"Edm.String\" Nullable=\"false\" MaxLengt" +
                "h=\"64\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"BURLT\" Type=\"Edm.St" +
                "ring\" Nullable=\"false\" MaxLength=\"164\" FixedLength=\"false\" Unicode=\"false\" /><Pr" +
                "operty Name=\"BURABRV\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"8\" FixedLeng" +
                "th=\"false\" Unicode=\"false\" /></EntityType><Association Name=\"USERSUSERS_TO_GROUP" +
                "S\"><End Type=\"MaxUserAndGroupModel.USER\" Role=\"USERS\" Multiplicity=\"1\" /><End Ty" +
                "pe=\"MaxUserAndGroupModel.USER_TO_GROUP\" Role=\"USERS_TO_GROUPS\" Multiplicity=\"*\" " +
                "/><ReferentialConstraint><Principal Role=\"USERS\"><PropertyRef Name=\"MF_USERID\" /" +
                "></Principal><Dependent Role=\"USERS_TO_GROUPS\"><PropertyRef";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = " Name=\"MF_USERID\" /></Dependent></ReferentialConstraint></Association><Associatio" +
                "n Name=\"GROUPSUSERS_TO_GROUPS\"><End Type=\"MaxUserAndGroupModel.GROUP\" Role=\"GROU" +
                "PS\" Multiplicity=\"1\" /><End Type=\"MaxUserAndGroupModel.USER_TO_GROUP\" Role=\"USER" +
                "S_TO_GROUPS\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"GROUPS\">" +
                "<PropertyRef Name=\"COMMUNITY_GROUP\" /></Principal><Dependent Role=\"USERS_TO_GROU" +
                "PS\"><PropertyRef Name=\"COMMUNITY_GROUP\" /></Dependent></ReferentialConstraint></" +
                "Association></Schema><Schema Namespace=\"MaxData\" xmlns=\"http://schemas.microsoft" +
                ".com/ado/2009/11/edm\"><EntityContainer Name=\"MaxUserAndGroupEntities\" m:IsDefaul" +
                "tEntityContainer=\"true\" p6:LazyLoadingEnabled=\"true\" xmlns:p6=\"http://schemas.mi" +
                "crosoft.com/ado/2009/02/edm/annotation\"><EntitySet Name=\"USERS\" EntityType=\"MaxU" +
                "serAndGroupModel.USER\" /><EntitySet Name=\"GROUPS\" EntityType=\"MaxUserAndGroupMod" +
                "el.GROUP\" /><EntitySet Name=\"USERS_TO_GROUPS\" EntityType=\"MaxUserAndGroupModel.U" +
                "SER_TO_GROUP\" /><EntitySet Name=\"USER_TABLEAU_SITES\" EntityType=\"MaxUserAndGroup" +
                "Model.USER_TABLEAU_SITES\" /><EntitySet Name=\"AGENCIES\" EntityType=\"MaxUserAndGro" +
                "upModel.AGENCY\" /><EntitySet Name=\"BUREAUS\" EntityType=\"MaxUserAndGroupModel.BUR" +
                "EAU\" /><AssociationSet Name=\"USERSUSERS_TO_GROUPS\" Association=\"MaxUserAndGroupM" +
                "odel.USERSUSERS_TO_GROUPS\"><End Role=\"USERS\" EntitySet=\"USERS\" /><End Role=\"USER" +
                "S_TO_GROUPS\" EntitySet=\"USERS_TO_GROUPS\" /></AssociationSet><AssociationSet Name" +
                "=\"GROUPSUSERS_TO_GROUPS\" Association=\"MaxUserAndGroupModel.GROUPSUSERS_TO_GROUPS" +
                "\"><End Role=\"GROUPS\" EntitySet=\"GROUPS\" /><End Role=\"USERS_TO_GROUPS\" EntitySet=" +
                "\"USERS_TO_GROUPS\" /></AssociationSet></EntityContainer></Schema></edmx:DataServi" +
                "ces></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for MaxUserAndGroupModel.USER in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MF_USERID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("MF_USERID")]
    public partial class USER
    {
        /// <summary>
        /// Create a new USER object.
        /// </summary>
        /// <param name="mF_USERID">Initial value of MF_USERID.</param>
        /// <param name="fIRST_NAME">Initial value of FIRST_NAME.</param>
        /// <param name="mIDDLE_NAME">Initial value of MIDDLE_NAME.</param>
        /// <param name="lAST_NAME">Initial value of LAST_NAME.</param>
        /// <param name="pHONE">Initial value of PHONE.</param>
        /// <param name="pHONE_EXT">Initial value of PHONE_EXT.</param>
        /// <param name="fAX">Initial value of FAX.</param>
        /// <param name="eMAIL">Initial value of EMAIL.</param>
        /// <param name="aDDRESS_1">Initial value of ADDRESS_1.</param>
        /// <param name="aDDRESS_2">Initial value of ADDRESS_2.</param>
        /// <param name="cITY">Initial value of CITY.</param>
        /// <param name="sTATE">Initial value of STATE.</param>
        /// <param name="zIPCODE">Initial value of ZIPCODE.</param>
        /// <param name="uSER_STATUS">Initial value of USER_STATUS.</param>
        /// <param name="uSER_CLASSIFICATION">Initial value of USER_CLASSIFICATION.</param>
        /// <param name="sDATETIME">Initial value of SDATETIME.</param>
        /// <param name="cOUNTRY_CODE">Initial value of COUNTRY_CODE.</param>
        /// <param name="oRG_BUREAU">Initial value of ORG_BUREAU.</param>
        /// <param name="aGEABRV">Initial value of AGEABRV.</param>
        /// <param name="tEST_ACCT_ID">Initial value of TEST_ACCT_ID.</param>
        /// <param name="aDMIN_ACCT_ID">Initial value of ADMIN_ACCT_ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static USER CreateUSER(
                    string mF_USERID, 
                    string fIRST_NAME, 
                    string mIDDLE_NAME, 
                    string lAST_NAME, 
                    string pHONE, 
                    string pHONE_EXT, 
                    string fAX, 
                    string eMAIL, 
                    string aDDRESS_1, 
                    string aDDRESS_2, 
                    string cITY, 
                    string sTATE, 
                    string zIPCODE, 
                    string uSER_STATUS, 
                    string uSER_CLASSIFICATION, 
                    global::System.DateTime sDATETIME, 
                    string cOUNTRY_CODE, 
                    string oRG_BUREAU, 
                    string aGEABRV, 
                    string tEST_ACCT_ID, 
                    string aDMIN_ACCT_ID)
        {
            USER uSER = new USER();
            uSER.MF_USERID = mF_USERID;
            uSER.FIRST_NAME = fIRST_NAME;
            uSER.MIDDLE_NAME = mIDDLE_NAME;
            uSER.LAST_NAME = lAST_NAME;
            uSER.PHONE = pHONE;
            uSER.PHONE_EXT = pHONE_EXT;
            uSER.FAX = fAX;
            uSER.EMAIL = eMAIL;
            uSER.ADDRESS_1 = aDDRESS_1;
            uSER.ADDRESS_2 = aDDRESS_2;
            uSER.CITY = cITY;
            uSER.STATE = sTATE;
            uSER.ZIPCODE = zIPCODE;
            uSER.USER_STATUS = uSER_STATUS;
            uSER.USER_CLASSIFICATION = uSER_CLASSIFICATION;
            uSER.SDATETIME = sDATETIME;
            uSER.COUNTRY_CODE = cOUNTRY_CODE;
            uSER.ORG_BUREAU = oRG_BUREAU;
            uSER.AGEABRV = aGEABRV;
            uSER.TEST_ACCT_ID = tEST_ACCT_ID;
            uSER.ADMIN_ACCT_ID = aDMIN_ACCT_ID;
            return uSER;
        }
        /// <summary>
        /// There are no comments for Property MF_USERID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MF_USERID
        {
            get
            {
                return this._MF_USERID;
            }
            set
            {
                this.OnMF_USERIDChanging(value);
                this._MF_USERID = value;
                this.OnMF_USERIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MF_USERID;
        partial void OnMF_USERIDChanging(string value);
        partial void OnMF_USERIDChanged();
        /// <summary>
        /// There are no comments for Property FIRST_NAME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FIRST_NAME
        {
            get
            {
                return this._FIRST_NAME;
            }
            set
            {
                this.OnFIRST_NAMEChanging(value);
                this._FIRST_NAME = value;
                this.OnFIRST_NAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FIRST_NAME;
        partial void OnFIRST_NAMEChanging(string value);
        partial void OnFIRST_NAMEChanged();
        /// <summary>
        /// There are no comments for Property MIDDLE_NAME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MIDDLE_NAME
        {
            get
            {
                return this._MIDDLE_NAME;
            }
            set
            {
                this.OnMIDDLE_NAMEChanging(value);
                this._MIDDLE_NAME = value;
                this.OnMIDDLE_NAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MIDDLE_NAME;
        partial void OnMIDDLE_NAMEChanging(string value);
        partial void OnMIDDLE_NAMEChanged();
        /// <summary>
        /// There are no comments for Property LAST_NAME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LAST_NAME
        {
            get
            {
                return this._LAST_NAME;
            }
            set
            {
                this.OnLAST_NAMEChanging(value);
                this._LAST_NAME = value;
                this.OnLAST_NAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LAST_NAME;
        partial void OnLAST_NAMEChanging(string value);
        partial void OnLAST_NAMEChanged();
        /// <summary>
        /// There are no comments for Property PHONE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PHONE
        {
            get
            {
                return this._PHONE;
            }
            set
            {
                this.OnPHONEChanging(value);
                this._PHONE = value;
                this.OnPHONEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PHONE;
        partial void OnPHONEChanging(string value);
        partial void OnPHONEChanged();
        /// <summary>
        /// There are no comments for Property PHONE_EXT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PHONE_EXT
        {
            get
            {
                return this._PHONE_EXT;
            }
            set
            {
                this.OnPHONE_EXTChanging(value);
                this._PHONE_EXT = value;
                this.OnPHONE_EXTChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PHONE_EXT;
        partial void OnPHONE_EXTChanging(string value);
        partial void OnPHONE_EXTChanged();
        /// <summary>
        /// There are no comments for Property FAX in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FAX
        {
            get
            {
                return this._FAX;
            }
            set
            {
                this.OnFAXChanging(value);
                this._FAX = value;
                this.OnFAXChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FAX;
        partial void OnFAXChanging(string value);
        partial void OnFAXChanged();
        /// <summary>
        /// There are no comments for Property EMAIL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EMAIL
        {
            get
            {
                return this._EMAIL;
            }
            set
            {
                this.OnEMAILChanging(value);
                this._EMAIL = value;
                this.OnEMAILChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EMAIL;
        partial void OnEMAILChanging(string value);
        partial void OnEMAILChanged();
        /// <summary>
        /// There are no comments for Property ADDRESS_1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ADDRESS_1
        {
            get
            {
                return this._ADDRESS_1;
            }
            set
            {
                this.OnADDRESS_1Changing(value);
                this._ADDRESS_1 = value;
                this.OnADDRESS_1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ADDRESS_1;
        partial void OnADDRESS_1Changing(string value);
        partial void OnADDRESS_1Changed();
        /// <summary>
        /// There are no comments for Property ADDRESS_2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ADDRESS_2
        {
            get
            {
                return this._ADDRESS_2;
            }
            set
            {
                this.OnADDRESS_2Changing(value);
                this._ADDRESS_2 = value;
                this.OnADDRESS_2Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ADDRESS_2;
        partial void OnADDRESS_2Changing(string value);
        partial void OnADDRESS_2Changed();
        /// <summary>
        /// There are no comments for Property CITY in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CITY
        {
            get
            {
                return this._CITY;
            }
            set
            {
                this.OnCITYChanging(value);
                this._CITY = value;
                this.OnCITYChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CITY;
        partial void OnCITYChanging(string value);
        partial void OnCITYChanged();
        /// <summary>
        /// There are no comments for Property STATE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string STATE
        {
            get
            {
                return this._STATE;
            }
            set
            {
                this.OnSTATEChanging(value);
                this._STATE = value;
                this.OnSTATEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _STATE;
        partial void OnSTATEChanging(string value);
        partial void OnSTATEChanged();
        /// <summary>
        /// There are no comments for Property ZIPCODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ZIPCODE
        {
            get
            {
                return this._ZIPCODE;
            }
            set
            {
                this.OnZIPCODEChanging(value);
                this._ZIPCODE = value;
                this.OnZIPCODEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ZIPCODE;
        partial void OnZIPCODEChanging(string value);
        partial void OnZIPCODEChanged();
        /// <summary>
        /// There are no comments for Property USER_STATUS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string USER_STATUS
        {
            get
            {
                return this._USER_STATUS;
            }
            set
            {
                this.OnUSER_STATUSChanging(value);
                this._USER_STATUS = value;
                this.OnUSER_STATUSChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _USER_STATUS;
        partial void OnUSER_STATUSChanging(string value);
        partial void OnUSER_STATUSChanged();
        /// <summary>
        /// There are no comments for Property USER_CLASSIFICATION in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string USER_CLASSIFICATION
        {
            get
            {
                return this._USER_CLASSIFICATION;
            }
            set
            {
                this.OnUSER_CLASSIFICATIONChanging(value);
                this._USER_CLASSIFICATION = value;
                this.OnUSER_CLASSIFICATIONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _USER_CLASSIFICATION;
        partial void OnUSER_CLASSIFICATIONChanging(string value);
        partial void OnUSER_CLASSIFICATIONChanged();
        /// <summary>
        /// There are no comments for Property UCASE_LAST_NAME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UCASE_LAST_NAME
        {
            get
            {
                return this._UCASE_LAST_NAME;
            }
            set
            {
                this.OnUCASE_LAST_NAMEChanging(value);
                this._UCASE_LAST_NAME = value;
                this.OnUCASE_LAST_NAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UCASE_LAST_NAME;
        partial void OnUCASE_LAST_NAMEChanging(string value);
        partial void OnUCASE_LAST_NAMEChanged();
        /// <summary>
        /// There are no comments for Property UCASE_FIRST_NAME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UCASE_FIRST_NAME
        {
            get
            {
                return this._UCASE_FIRST_NAME;
            }
            set
            {
                this.OnUCASE_FIRST_NAMEChanging(value);
                this._UCASE_FIRST_NAME = value;
                this.OnUCASE_FIRST_NAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UCASE_FIRST_NAME;
        partial void OnUCASE_FIRST_NAMEChanging(string value);
        partial void OnUCASE_FIRST_NAMEChanged();
        /// <summary>
        /// There are no comments for Property UCASE_MIDDLE_NAME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UCASE_MIDDLE_NAME
        {
            get
            {
                return this._UCASE_MIDDLE_NAME;
            }
            set
            {
                this.OnUCASE_MIDDLE_NAMEChanging(value);
                this._UCASE_MIDDLE_NAME = value;
                this.OnUCASE_MIDDLE_NAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UCASE_MIDDLE_NAME;
        partial void OnUCASE_MIDDLE_NAMEChanging(string value);
        partial void OnUCASE_MIDDLE_NAMEChanged();
        /// <summary>
        /// There are no comments for Property LDAP_EMAIL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LDAP_EMAIL
        {
            get
            {
                return this._LDAP_EMAIL;
            }
            set
            {
                this.OnLDAP_EMAILChanging(value);
                this._LDAP_EMAIL = value;
                this.OnLDAP_EMAILChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LDAP_EMAIL;
        partial void OnLDAP_EMAILChanging(string value);
        partial void OnLDAP_EMAILChanged();
        /// <summary>
        /// There are no comments for Property SDATETIME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime SDATETIME
        {
            get
            {
                return this._SDATETIME;
            }
            set
            {
                this.OnSDATETIMEChanging(value);
                this._SDATETIME = value;
                this.OnSDATETIMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _SDATETIME;
        partial void OnSDATETIMEChanging(global::System.DateTime value);
        partial void OnSDATETIMEChanged();
        /// <summary>
        /// There are no comments for Property ORGANIZATION in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ORGANIZATION
        {
            get
            {
                return this._ORGANIZATION;
            }
            set
            {
                this.OnORGANIZATIONChanging(value);
                this._ORGANIZATION = value;
                this.OnORGANIZATIONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ORGANIZATION;
        partial void OnORGANIZATIONChanging(string value);
        partial void OnORGANIZATIONChanged();
        /// <summary>
        /// There are no comments for Property COUNTRY_CODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COUNTRY_CODE
        {
            get
            {
                return this._COUNTRY_CODE;
            }
            set
            {
                this.OnCOUNTRY_CODEChanging(value);
                this._COUNTRY_CODE = value;
                this.OnCOUNTRY_CODEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COUNTRY_CODE;
        partial void OnCOUNTRY_CODEChanging(string value);
        partial void OnCOUNTRY_CODEChanged();
        /// <summary>
        /// There are no comments for Property ORG_AGENCY in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ORG_AGENCY
        {
            get
            {
                return this._ORG_AGENCY;
            }
            set
            {
                this.OnORG_AGENCYChanging(value);
                this._ORG_AGENCY = value;
                this.OnORG_AGENCYChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ORG_AGENCY;
        partial void OnORG_AGENCYChanging(string value);
        partial void OnORG_AGENCYChanged();
        /// <summary>
        /// There are no comments for Property ORG_BUREAU in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ORG_BUREAU
        {
            get
            {
                return this._ORG_BUREAU;
            }
            set
            {
                this.OnORG_BUREAUChanging(value);
                this._ORG_BUREAU = value;
                this.OnORG_BUREAUChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ORG_BUREAU;
        partial void OnORG_BUREAUChanging(string value);
        partial void OnORG_BUREAUChanged();
        /// <summary>
        /// There are no comments for Property AGEABRV in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AGEABRV
        {
            get
            {
                return this._AGEABRV;
            }
            set
            {
                this.OnAGEABRVChanging(value);
                this._AGEABRV = value;
                this.OnAGEABRVChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AGEABRV;
        partial void OnAGEABRVChanging(string value);
        partial void OnAGEABRVChanged();
        /// <summary>
        /// There are no comments for Property TEST_ACCT_ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TEST_ACCT_ID
        {
            get
            {
                return this._TEST_ACCT_ID;
            }
            set
            {
                this.OnTEST_ACCT_IDChanging(value);
                this._TEST_ACCT_ID = value;
                this.OnTEST_ACCT_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TEST_ACCT_ID;
        partial void OnTEST_ACCT_IDChanging(string value);
        partial void OnTEST_ACCT_IDChanged();
        /// <summary>
        /// There are no comments for Property ADMIN_ACCT_ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ADMIN_ACCT_ID
        {
            get
            {
                return this._ADMIN_ACCT_ID;
            }
            set
            {
                this.OnADMIN_ACCT_IDChanging(value);
                this._ADMIN_ACCT_ID = value;
                this.OnADMIN_ACCT_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ADMIN_ACCT_ID;
        partial void OnADMIN_ACCT_IDChanging(string value);
        partial void OnADMIN_ACCT_IDChanged();
        /// <summary>
        /// There are no comments for USER_TO_USERS_TO_GROUPS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<USER_TO_GROUP> USER_TO_USERS_TO_GROUPS
        {
            get
            {
                return this._USER_TO_USERS_TO_GROUPS;
            }
            set
            {
                if ((value != null))
                {
                    this._USER_TO_USERS_TO_GROUPS = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<USER_TO_GROUP> _USER_TO_USERS_TO_GROUPS = new global::System.Collections.ObjectModel.Collection<USER_TO_GROUP>();
    }
    /// <summary>
    /// There are no comments for MaxUserAndGroupModel.GROUP in the schema.
    /// </summary>
    /// <KeyProperties>
    /// COMMUNITY_GROUP
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("COMMUNITY_GROUP")]
    public partial class GROUP
    {
        /// <summary>
        /// Create a new GROUP object.
        /// </summary>
        /// <param name="cOMMUNITY_GROUP">Initial value of COMMUNITY_GROUP.</param>
        /// <param name="cOMMUNITY_GROUPNAME">Initial value of COMMUNITY_GROUPNAME.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static GROUP CreateGROUP(string cOMMUNITY_GROUP, string cOMMUNITY_GROUPNAME)
        {
            GROUP gROUP = new GROUP();
            gROUP.COMMUNITY_GROUP = cOMMUNITY_GROUP;
            gROUP.COMMUNITY_GROUPNAME = cOMMUNITY_GROUPNAME;
            return gROUP;
        }
        /// <summary>
        /// There are no comments for Property COMMUNITY_GROUP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COMMUNITY_GROUP
        {
            get
            {
                return this._COMMUNITY_GROUP;
            }
            set
            {
                this.OnCOMMUNITY_GROUPChanging(value);
                this._COMMUNITY_GROUP = value;
                this.OnCOMMUNITY_GROUPChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COMMUNITY_GROUP;
        partial void OnCOMMUNITY_GROUPChanging(string value);
        partial void OnCOMMUNITY_GROUPChanged();
        /// <summary>
        /// There are no comments for Property COMMUNITY_GROUPNAME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COMMUNITY_GROUPNAME
        {
            get
            {
                return this._COMMUNITY_GROUPNAME;
            }
            set
            {
                this.OnCOMMUNITY_GROUPNAMEChanging(value);
                this._COMMUNITY_GROUPNAME = value;
                this.OnCOMMUNITY_GROUPNAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COMMUNITY_GROUPNAME;
        partial void OnCOMMUNITY_GROUPNAMEChanging(string value);
        partial void OnCOMMUNITY_GROUPNAMEChanged();
        /// <summary>
        /// There are no comments for GROUP_TO_USERS_TO_GROUPS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<USER_TO_GROUP> GROUP_TO_USERS_TO_GROUPS
        {
            get
            {
                return this._GROUP_TO_USERS_TO_GROUPS;
            }
            set
            {
                if ((value != null))
                {
                    this._GROUP_TO_USERS_TO_GROUPS = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<USER_TO_GROUP> _GROUP_TO_USERS_TO_GROUPS = new global::System.Collections.ObjectModel.Collection<USER_TO_GROUP>();
    }
    /// <summary>
    /// There are no comments for MaxUserAndGroupModel.USER_TO_GROUP in the schema.
    /// </summary>
    /// <KeyProperties>
    /// COMMUNITY_GROUP
    /// MF_USERID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("COMMUNITY_GROUP", "MF_USERID")]
    public partial class USER_TO_GROUP
    {
        /// <summary>
        /// Create a new USER_TO_GROUP object.
        /// </summary>
        /// <param name="mF_USERID">Initial value of MF_USERID.</param>
        /// <param name="cOMMUNITY_GROUP">Initial value of COMMUNITY_GROUP.</param>
        /// <param name="cOMMUNITY_GROUPNAME">Initial value of COMMUNITY_GROUPNAME.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static USER_TO_GROUP CreateUSER_TO_GROUP(string mF_USERID, string cOMMUNITY_GROUP, string cOMMUNITY_GROUPNAME)
        {
            USER_TO_GROUP uSER_TO_GROUP = new USER_TO_GROUP();
            uSER_TO_GROUP.MF_USERID = mF_USERID;
            uSER_TO_GROUP.COMMUNITY_GROUP = cOMMUNITY_GROUP;
            uSER_TO_GROUP.COMMUNITY_GROUPNAME = cOMMUNITY_GROUPNAME;
            return uSER_TO_GROUP;
        }
        /// <summary>
        /// There are no comments for Property MF_USERID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MF_USERID
        {
            get
            {
                return this._MF_USERID;
            }
            set
            {
                this.OnMF_USERIDChanging(value);
                this._MF_USERID = value;
                this.OnMF_USERIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MF_USERID;
        partial void OnMF_USERIDChanging(string value);
        partial void OnMF_USERIDChanged();
        /// <summary>
        /// There are no comments for Property COMMUNITY_GROUP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COMMUNITY_GROUP
        {
            get
            {
                return this._COMMUNITY_GROUP;
            }
            set
            {
                this.OnCOMMUNITY_GROUPChanging(value);
                this._COMMUNITY_GROUP = value;
                this.OnCOMMUNITY_GROUPChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COMMUNITY_GROUP;
        partial void OnCOMMUNITY_GROUPChanging(string value);
        partial void OnCOMMUNITY_GROUPChanged();
        /// <summary>
        /// There are no comments for Property COMMUNITY_GROUPNAME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COMMUNITY_GROUPNAME
        {
            get
            {
                return this._COMMUNITY_GROUPNAME;
            }
            set
            {
                this.OnCOMMUNITY_GROUPNAMEChanging(value);
                this._COMMUNITY_GROUPNAME = value;
                this.OnCOMMUNITY_GROUPNAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COMMUNITY_GROUPNAME;
        partial void OnCOMMUNITY_GROUPNAMEChanging(string value);
        partial void OnCOMMUNITY_GROUPNAMEChanged();
        /// <summary>
        /// There are no comments for USER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public USER USER
        {
            get
            {
                return this._USER;
            }
            set
            {
                this._USER = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private USER _USER;
        /// <summary>
        /// There are no comments for GROUP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public GROUP GROUP
        {
            get
            {
                return this._GROUP;
            }
            set
            {
                this._GROUP = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private GROUP _GROUP;
    }
    /// <summary>
    /// There are no comments for MaxUserAndGroupModel.USER_TABLEAU_SITES in the schema.
    /// </summary>
    /// <KeyProperties>
    /// COMMUNITY_GROUP
    /// MF_USERID
    /// TABLEAU_SITE
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("COMMUNITY_GROUP", "MF_USERID", "TABLEAU_SITE")]
    public partial class USER_TABLEAU_SITES
    {
        /// <summary>
        /// Create a new USER_TABLEAU_SITES object.
        /// </summary>
        /// <param name="mF_USERID">Initial value of MF_USERID.</param>
        /// <param name="cOMMUNITY_GROUP">Initial value of COMMUNITY_GROUP.</param>
        /// <param name="tABLEAU_SITE">Initial value of TABLEAU_SITE.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static USER_TABLEAU_SITES CreateUSER_TABLEAU_SITES(string mF_USERID, string cOMMUNITY_GROUP, string tABLEAU_SITE)
        {
            USER_TABLEAU_SITES uSER_TABLEAU_SITES = new USER_TABLEAU_SITES();
            uSER_TABLEAU_SITES.MF_USERID = mF_USERID;
            uSER_TABLEAU_SITES.COMMUNITY_GROUP = cOMMUNITY_GROUP;
            uSER_TABLEAU_SITES.TABLEAU_SITE = tABLEAU_SITE;
            return uSER_TABLEAU_SITES;
        }
        /// <summary>
        /// There are no comments for Property LDAP_EMAIL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LDAP_EMAIL
        {
            get
            {
                return this._LDAP_EMAIL;
            }
            set
            {
                this.OnLDAP_EMAILChanging(value);
                this._LDAP_EMAIL = value;
                this.OnLDAP_EMAILChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LDAP_EMAIL;
        partial void OnLDAP_EMAILChanging(string value);
        partial void OnLDAP_EMAILChanged();
        /// <summary>
        /// There are no comments for Property MF_USERID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MF_USERID
        {
            get
            {
                return this._MF_USERID;
            }
            set
            {
                this.OnMF_USERIDChanging(value);
                this._MF_USERID = value;
                this.OnMF_USERIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MF_USERID;
        partial void OnMF_USERIDChanging(string value);
        partial void OnMF_USERIDChanged();
        /// <summary>
        /// There are no comments for Property COMMUNITY_GROUP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COMMUNITY_GROUP
        {
            get
            {
                return this._COMMUNITY_GROUP;
            }
            set
            {
                this.OnCOMMUNITY_GROUPChanging(value);
                this._COMMUNITY_GROUP = value;
                this.OnCOMMUNITY_GROUPChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COMMUNITY_GROUP;
        partial void OnCOMMUNITY_GROUPChanging(string value);
        partial void OnCOMMUNITY_GROUPChanged();
        /// <summary>
        /// There are no comments for Property TABLEAU_SITE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TABLEAU_SITE
        {
            get
            {
                return this._TABLEAU_SITE;
            }
            set
            {
                this.OnTABLEAU_SITEChanging(value);
                this._TABLEAU_SITE = value;
                this.OnTABLEAU_SITEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TABLEAU_SITE;
        partial void OnTABLEAU_SITEChanging(string value);
        partial void OnTABLEAU_SITEChanged();
    }
    /// <summary>
    /// There are no comments for MaxUserAndGroupModel.AGENCY in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ORG_AGENCY
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ORG_AGENCY")]
    public partial class AGENCY
    {
        /// <summary>
        /// Create a new AGENCY object.
        /// </summary>
        /// <param name="oRG_AGENCY">Initial value of ORG_AGENCY.</param>
        /// <param name="aGEAI">Initial value of AGEAI.</param>
        /// <param name="aGEST">Initial value of AGEST.</param>
        /// <param name="aGETL">Initial value of AGETL.</param>
        /// <param name="aGELT">Initial value of AGELT.</param>
        /// <param name="aGEABRV">Initial value of AGEABRV.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AGENCY CreateAGENCY(string oRG_AGENCY, string aGEAI, string aGEST, string aGETL, string aGELT, string aGEABRV)
        {
            AGENCY aGENCY = new AGENCY();
            aGENCY.ORG_AGENCY = oRG_AGENCY;
            aGENCY.AGEAI = aGEAI;
            aGENCY.AGEST = aGEST;
            aGENCY.AGETL = aGETL;
            aGENCY.AGELT = aGELT;
            aGENCY.AGEABRV = aGEABRV;
            return aGENCY;
        }
        /// <summary>
        /// There are no comments for Property ORG_AGENCY in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ORG_AGENCY
        {
            get
            {
                return this._ORG_AGENCY;
            }
            set
            {
                this.OnORG_AGENCYChanging(value);
                this._ORG_AGENCY = value;
                this.OnORG_AGENCYChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ORG_AGENCY;
        partial void OnORG_AGENCYChanging(string value);
        partial void OnORG_AGENCYChanged();
        /// <summary>
        /// There are no comments for Property AGEAI in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AGEAI
        {
            get
            {
                return this._AGEAI;
            }
            set
            {
                this.OnAGEAIChanging(value);
                this._AGEAI = value;
                this.OnAGEAIChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AGEAI;
        partial void OnAGEAIChanging(string value);
        partial void OnAGEAIChanged();
        /// <summary>
        /// There are no comments for Property AGEST in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AGEST
        {
            get
            {
                return this._AGEST;
            }
            set
            {
                this.OnAGESTChanging(value);
                this._AGEST = value;
                this.OnAGESTChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AGEST;
        partial void OnAGESTChanging(string value);
        partial void OnAGESTChanged();
        /// <summary>
        /// There are no comments for Property AGETL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AGETL
        {
            get
            {
                return this._AGETL;
            }
            set
            {
                this.OnAGETLChanging(value);
                this._AGETL = value;
                this.OnAGETLChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AGETL;
        partial void OnAGETLChanging(string value);
        partial void OnAGETLChanged();
        /// <summary>
        /// There are no comments for Property AGELT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AGELT
        {
            get
            {
                return this._AGELT;
            }
            set
            {
                this.OnAGELTChanging(value);
                this._AGELT = value;
                this.OnAGELTChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AGELT;
        partial void OnAGELTChanging(string value);
        partial void OnAGELTChanged();
        /// <summary>
        /// There are no comments for Property AGEABRV in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AGEABRV
        {
            get
            {
                return this._AGEABRV;
            }
            set
            {
                this.OnAGEABRVChanging(value);
                this._AGEABRV = value;
                this.OnAGEABRVChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AGEABRV;
        partial void OnAGEABRVChanging(string value);
        partial void OnAGEABRVChanged();
    }
    /// <summary>
    /// There are no comments for MaxUserAndGroupModel.BUREAU in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ORG_AGENCY
    /// ORG_BUREAU
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ORG_AGENCY", "ORG_BUREAU")]
    public partial class BUREAU
    {
        /// <summary>
        /// Create a new BUREAU object.
        /// </summary>
        /// <param name="oRG_AGENCY">Initial value of ORG_AGENCY.</param>
        /// <param name="oRG_BUREAU">Initial value of ORG_BUREAU.</param>
        /// <param name="bURSEQ">Initial value of BURSEQ.</param>
        /// <param name="bURAI">Initial value of BURAI.</param>
        /// <param name="bURST">Initial value of BURST.</param>
        /// <param name="bURTL">Initial value of BURTL.</param>
        /// <param name="bURLT">Initial value of BURLT.</param>
        /// <param name="bURABRV">Initial value of BURABRV.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static BUREAU CreateBUREAU(string oRG_AGENCY, string oRG_BUREAU, string bURSEQ, string bURAI, string bURST, string bURTL, string bURLT, string bURABRV)
        {
            BUREAU bUREAU = new BUREAU();
            bUREAU.ORG_AGENCY = oRG_AGENCY;
            bUREAU.ORG_BUREAU = oRG_BUREAU;
            bUREAU.BURSEQ = bURSEQ;
            bUREAU.BURAI = bURAI;
            bUREAU.BURST = bURST;
            bUREAU.BURTL = bURTL;
            bUREAU.BURLT = bURLT;
            bUREAU.BURABRV = bURABRV;
            return bUREAU;
        }
        /// <summary>
        /// There are no comments for Property ORG_AGENCY in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ORG_AGENCY
        {
            get
            {
                return this._ORG_AGENCY;
            }
            set
            {
                this.OnORG_AGENCYChanging(value);
                this._ORG_AGENCY = value;
                this.OnORG_AGENCYChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ORG_AGENCY;
        partial void OnORG_AGENCYChanging(string value);
        partial void OnORG_AGENCYChanged();
        /// <summary>
        /// There are no comments for Property ORG_BUREAU in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ORG_BUREAU
        {
            get
            {
                return this._ORG_BUREAU;
            }
            set
            {
                this.OnORG_BUREAUChanging(value);
                this._ORG_BUREAU = value;
                this.OnORG_BUREAUChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ORG_BUREAU;
        partial void OnORG_BUREAUChanging(string value);
        partial void OnORG_BUREAUChanged();
        /// <summary>
        /// There are no comments for Property BURSEQ in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BURSEQ
        {
            get
            {
                return this._BURSEQ;
            }
            set
            {
                this.OnBURSEQChanging(value);
                this._BURSEQ = value;
                this.OnBURSEQChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BURSEQ;
        partial void OnBURSEQChanging(string value);
        partial void OnBURSEQChanged();
        /// <summary>
        /// There are no comments for Property BURAI in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BURAI
        {
            get
            {
                return this._BURAI;
            }
            set
            {
                this.OnBURAIChanging(value);
                this._BURAI = value;
                this.OnBURAIChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BURAI;
        partial void OnBURAIChanging(string value);
        partial void OnBURAIChanged();
        /// <summary>
        /// There are no comments for Property BURST in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BURST
        {
            get
            {
                return this._BURST;
            }
            set
            {
                this.OnBURSTChanging(value);
                this._BURST = value;
                this.OnBURSTChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BURST;
        partial void OnBURSTChanging(string value);
        partial void OnBURSTChanged();
        /// <summary>
        /// There are no comments for Property BURTL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BURTL
        {
            get
            {
                return this._BURTL;
            }
            set
            {
                this.OnBURTLChanging(value);
                this._BURTL = value;
                this.OnBURTLChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BURTL;
        partial void OnBURTLChanging(string value);
        partial void OnBURTLChanged();
        /// <summary>
        /// There are no comments for Property BURLT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BURLT
        {
            get
            {
                return this._BURLT;
            }
            set
            {
                this.OnBURLTChanging(value);
                this._BURLT = value;
                this.OnBURLTChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BURLT;
        partial void OnBURLTChanging(string value);
        partial void OnBURLTChanged();
        /// <summary>
        /// There are no comments for Property BURABRV in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BURABRV
        {
            get
            {
                return this._BURABRV;
            }
            set
            {
                this.OnBURABRVChanging(value);
                this._BURABRV = value;
                this.OnBURABRVChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BURABRV;
        partial void OnBURABRVChanging(string value);
        partial void OnBURABRVChanged();
    }
}
