// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mod.Framework.User;

namespace Mod.Framework.User.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20210126151018_AddUnassignedDepartment")]
    partial class AddUnassignedDepartment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mod.Framework.User.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdSecurityGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "DIR",
                            AdSecurityGroup = "OMB_DIR",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office of the Director"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Statutory Offices",
                            ParentDepartmentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OMB-Wide Support Offices",
                            ParentDepartmentId = 1
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "LA",
                            AdSecurityGroup = "SG-OMB-Legislative_Affairs",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Legislative Affairs",
                            ParentDepartmentId = 5
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = true,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Strategic Planning & Communications",
                            ParentDepartmentId = 5
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "MOD",
                            AdSecurityGroup = "OMB_ADM",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Management and Operations Division",
                            ParentDepartmentId = 5
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "GC",
                            AdSecurityGroup = "OMB_GC",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "General Counsel",
                            ParentDepartmentId = 5
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "EP",
                            AdSecurityGroup = "OMB ECON",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Economic Policy",
                            ParentDepartmentId = 5
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "LRD",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Legislative Reference Division",
                            ParentDepartmentId = 5
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "ESGG",
                            AdSecurityGroup = "OMB_LRD_ESGG",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Economics, Science, Gen. Govt. Branch",
                            ParentDepartmentId = 11
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "HEVS",
                            AdSecurityGroup = "OMB_LRD_HEVS",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Health, Education, Veterans & Social Programs Branch",
                            ParentDepartmentId = 11
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "RDI",
                            AdSecurityGroup = "OMB_LRD_RDI",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Resources, Defense, International Branch",
                            ParentDepartmentId = 11
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "BR",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Budget Review",
                            ParentDepartmentId = 5
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "BASD",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Budget Analysis & Systems Division",
                            ParentDepartmentId = 15
                        },
                        new
                        {
                            Id = 17,
                            Abbreviation = "BAB",
                            AdSecurityGroup = "OMB_BR_BASD_BAB",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Budget Analysis Branch",
                            ParentDepartmentId = 16
                        },
                        new
                        {
                            Id = 18,
                            Abbreviation = "BSB",
                            AdSecurityGroup = "OMB_BR_BASD_BSB",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Budget Systems Branch",
                            ParentDepartmentId = 16
                        },
                        new
                        {
                            Id = 19,
                            Abbreviation = "BRCD",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Budget Review & Concepts Division",
                            ParentDepartmentId = 15
                        },
                        new
                        {
                            Id = 20,
                            Abbreviation = "BRB",
                            AdSecurityGroup = "OMB_BR_BRCD_BRB",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Budget Review Branch",
                            ParentDepartmentId = 19
                        },
                        new
                        {
                            Id = 21,
                            Abbreviation = "BCB",
                            AdSecurityGroup = "OMB_BR_BRCD_BCB",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Budget Concept Branch",
                            ParentDepartmentId = 19
                        },
                        new
                        {
                            Id = 22,
                            Abbreviation = "OPPM",
                            AdSecurityGroup = "SG-OMB-BPU",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office of Performance and Personnel Management",
                            ParentDepartmentId = 5
                        },
                        new
                        {
                            Id = 23,
                            Abbreviation = "",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = true,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Performance Unit",
                            ParentDepartmentId = 22
                        },
                        new
                        {
                            Id = 24,
                            Abbreviation = "",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = true,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Personnel Unit",
                            ParentDepartmentId = 22
                        },
                        new
                        {
                            Id = 25,
                            Abbreviation = "USDS",
                            AdSecurityGroup = "SG-OMB-USDS",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "U.S. Digital Service",
                            ParentDepartmentId = 5
                        },
                        new
                        {
                            Id = 27,
                            Abbreviation = "OFFM",
                            AdSecurityGroup = "OMB_OFFM_CAL",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office of Federal Financial Management",
                            ParentDepartmentId = 4
                        },
                        new
                        {
                            Id = 28,
                            Abbreviation = "FIRM",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Financial Integrity and Risk Management Branch",
                            ParentDepartmentId = 27
                        },
                        new
                        {
                            Id = 29,
                            Abbreviation = "MCAB",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Management Controls and Assistance Branch",
                            ParentDepartmentId = 27
                        },
                        new
                        {
                            Id = 30,
                            Abbreviation = "OFPP",
                            AdSecurityGroup = "OMB_OFPP",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office of Federal Procurement Policy",
                            ParentDepartmentId = 4
                        },
                        new
                        {
                            Id = 89,
                            Abbreviation = "",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Efficiency, Data, and Workforce Management Branch",
                            ParentDepartmentId = 30
                        },
                        new
                        {
                            Id = 90,
                            Abbreviation = "PDI",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Policy Development and Innovation Branch",
                            ParentDepartmentId = 30
                        },
                        new
                        {
                            Id = 31,
                            Abbreviation = "OFCIO",
                            AdSecurityGroup = "SG-OMB-OCIO",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office of the Federal Chief Information Officer",
                            ParentDepartmentId = 4
                        },
                        new
                        {
                            Id = 32,
                            Abbreviation = "",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Agency Oversight",
                            ParentDepartmentId = 31
                        },
                        new
                        {
                            Id = 33,
                            Abbreviation = "",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cyber and National Security Unit",
                            ParentDepartmentId = 31
                        },
                        new
                        {
                            Id = 34,
                            Abbreviation = "",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Policy, Budget, and Communications Unit",
                            ParentDepartmentId = 31
                        },
                        new
                        {
                            Id = 35,
                            Abbreviation = "OIRA",
                            AdSecurityGroup = "OMB_OIRA_NR",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office of Information & Regulatory Affairs",
                            ParentDepartmentId = 4
                        },
                        new
                        {
                            Id = 36,
                            Abbreviation = "FHLB",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Food, Health, and Labor Branch",
                            ParentDepartmentId = 35
                        },
                        new
                        {
                            Id = 37,
                            Abbreviation = "IPB",
                            AdSecurityGroup = "SG-OMB-OIRA-IPT",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Information Policy Branch",
                            ParentDepartmentId = 35
                        },
                        new
                        {
                            Id = 38,
                            Abbreviation = "NREB",
                            AdSecurityGroup = "OMB_OIRA_HRH",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Natural Resources and Environment Branch",
                            ParentDepartmentId = 35
                        },
                        new
                        {
                            Id = 39,
                            Abbreviation = "Privacy",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Privacy Branch",
                            ParentDepartmentId = 35
                        },
                        new
                        {
                            Id = 40,
                            Abbreviation = "SSP",
                            AdSecurityGroup = "OMB_OIRA_SP",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Statistical & Science Policy Branch",
                            ParentDepartmentId = 35
                        },
                        new
                        {
                            Id = 41,
                            Abbreviation = "TSB",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Transportation and Security Branch",
                            ParentDepartmentId = 35
                        },
                        new
                        {
                            Id = 43,
                            Abbreviation = "RMO",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Resource Management Offices",
                            ParentDepartmentId = 1
                        },
                        new
                        {
                            Id = 44,
                            Abbreviation = "NRP",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Natural Resource Programs",
                            ParentDepartmentId = 43
                        },
                        new
                        {
                            Id = 45,
                            Abbreviation = "ESWD",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Energy, Science & Water Division",
                            ParentDepartmentId = 44
                        },
                        new
                        {
                            Id = 46,
                            Abbreviation = "EB",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Energy Branch",
                            ParentDepartmentId = 45
                        },
                        new
                        {
                            Id = 47,
                            Abbreviation = "SSB",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Science & Space Branch",
                            ParentDepartmentId = 45
                        },
                        new
                        {
                            Id = 48,
                            Abbreviation = "WPB",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Water and Power Branch",
                            ParentDepartmentId = 45
                        },
                        new
                        {
                            Id = 49,
                            Abbreviation = "NRD",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Natural Resources Division",
                            ParentDepartmentId = 44
                        },
                        new
                        {
                            Id = 50,
                            Abbreviation = "AB",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Agriculture Branch",
                            ParentDepartmentId = 49
                        },
                        new
                        {
                            Id = 51,
                            Abbreviation = "EB",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Environment Branch",
                            ParentDepartmentId = 49
                        },
                        new
                        {
                            Id = 52,
                            Abbreviation = "IB",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Interior Branch",
                            ParentDepartmentId = 49
                        },
                        new
                        {
                            Id = 53,
                            Abbreviation = "EIML",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Education, Income, Maintenance, and Labor Programs",
                            ParentDepartmentId = 43
                        },
                        new
                        {
                            Id = 54,
                            Abbreviation = "EIML",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Education, Income, Maintenance, and Labor Division",
                            ParentDepartmentId = 53
                        },
                        new
                        {
                            Id = 55,
                            Abbreviation = "EIML",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Education Branch",
                            ParentDepartmentId = 54
                        },
                        new
                        {
                            Id = 56,
                            Abbreviation = "EIML",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Income Maintenance Branch",
                            ParentDepartmentId = 54
                        },
                        new
                        {
                            Id = 57,
                            Abbreviation = "EIML",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Labor Branch",
                            ParentDepartmentId = 54
                        },
                        new
                        {
                            Id = 58,
                            Abbreviation = "Health",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Health Programs",
                            ParentDepartmentId = 43
                        },
                        new
                        {
                            Id = 59,
                            Abbreviation = "HD",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Health Division",
                            ParentDepartmentId = 58
                        },
                        new
                        {
                            Id = 60,
                            Abbreviation = "HHS",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Health & Human Services Branch",
                            ParentDepartmentId = 59
                        },
                        new
                        {
                            Id = 61,
                            Abbreviation = "Medicain",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Medicaid Branch",
                            ParentDepartmentId = 59
                        },
                        new
                        {
                            Id = 62,
                            Abbreviation = "Medicain",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Medicare Branch",
                            ParentDepartmentId = 59
                        },
                        new
                        {
                            Id = 63,
                            Abbreviation = "PHB",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Public Health Branch",
                            ParentDepartmentId = 59
                        },
                        new
                        {
                            Id = 64,
                            Abbreviation = "",
                            AdSecurityGroup = "HIDA",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Health Insurance, Data, and Analysis Branch",
                            ParentDepartmentId = 59
                        },
                        new
                        {
                            Id = 65,
                            Abbreviation = "GGP",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "General Government Programs",
                            ParentDepartmentId = 43
                        },
                        new
                        {
                            Id = 66,
                            Abbreviation = "THJS",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Transportation, Homeland, Justice & Services Division",
                            ParentDepartmentId = 65
                        },
                        new
                        {
                            Id = 67,
                            Abbreviation = "TGB",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Transportation/GSA Branch",
                            ParentDepartmentId = 66
                        },
                        new
                        {
                            Id = 68,
                            Abbreviation = "HSB",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Homeland Security Branch",
                            ParentDepartmentId = 66
                        },
                        new
                        {
                            Id = 69,
                            Abbreviation = "Justice",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Justice Branch",
                            ParentDepartmentId = 66
                        },
                        new
                        {
                            Id = 70,
                            Abbreviation = "HTC",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Housing, Treasury, & Comm. Division",
                            ParentDepartmentId = 65
                        },
                        new
                        {
                            Id = 71,
                            Abbreviation = "Housing",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Housing Branch",
                            ParentDepartmentId = 70
                        },
                        new
                        {
                            Id = 72,
                            Abbreviation = "Treasury",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Treasury Branch",
                            ParentDepartmentId = 70
                        },
                        new
                        {
                            Id = 73,
                            Abbreviation = "Commerce",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Commerce Branch",
                            ParentDepartmentId = 70
                        },
                        new
                        {
                            Id = 74,
                            Abbreviation = "NSP",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "National Security Programs",
                            ParentDepartmentId = 43
                        },
                        new
                        {
                            Id = 75,
                            Abbreviation = "IAD",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "International Affairs Division",
                            ParentDepartmentId = 74
                        },
                        new
                        {
                            Id = 76,
                            Abbreviation = "State",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State Branch",
                            ParentDepartmentId = 75
                        },
                        new
                        {
                            Id = 77,
                            Abbreviation = "EAB",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Economic Affairs Branch",
                            ParentDepartmentId = 75
                        },
                        new
                        {
                            Id = 78,
                            Abbreviation = "NSD",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "National Security Division",
                            ParentDepartmentId = 74
                        },
                        new
                        {
                            Id = 87,
                            Abbreviation = "",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Defense Investments Branch",
                            ParentDepartmentId = 78
                        },
                        new
                        {
                            Id = 79,
                            Abbreviation = "NSP",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Command, Control, Comms, Computers, & Intelligence Branch",
                            ParentDepartmentId = 78
                        },
                        new
                        {
                            Id = 80,
                            Abbreviation = "NSP",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Defense Operations Branch",
                            ParentDepartmentId = 78
                        },
                        new
                        {
                            Id = 81,
                            Abbreviation = "NSP",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = true,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Force Structure & Investment Branch",
                            ParentDepartmentId = 78
                        },
                        new
                        {
                            Id = 82,
                            Abbreviation = "NSP",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Veterans Affairs & Defense Health Branch",
                            ParentDepartmentId = 78
                        },
                        new
                        {
                            Id = 91,
                            Abbreviation = "",
                            AdSecurityGroup = "",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unassigned",
                            ParentDepartmentId = 91
                        });
                });

            modelBuilder.Entity("Mod.Framework.User.Entities.DepartmentMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DepartmentMap");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Division = "Directors Office",
                            Office = "Deputy Director for Management's Office (DD/M)"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Division = "Directors Office",
                            Office = ""
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Division = "Directors Office",
                            Office = "Intellectual Property Enforcement Coordinators (IPEC) Office"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 55,
                            Division = "Education, Income Maintenance and Labor Programs",
                            Office = "Education Branch"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 53,
                            Division = "Education, Income Maintenance and Labor Programs",
                            Office = "Office of the Associate Director, EIML"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 54,
                            Division = "Education, Income Maintenance and Labor Programs",
                            Office = "Office of the Deputy Associate Director, EIML"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 56,
                            Division = "Education, Income Maintenance and Labor Programs",
                            Office = "Income Maintenance Branch"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 57,
                            Division = "Education, Income Maintenance and Labor Programs",
                            Office = "Labor Branch"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 73,
                            Division = "General Government Programs",
                            Office = "Commerce Branch"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 65,
                            Division = "General Government Programs",
                            Office = "Office Of the Associate Director, GGP"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 68,
                            Division = "General Government Programs",
                            Office = "Homeland Security Branch"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 71,
                            Division = "General Government Programs",
                            Office = "Housing Branch"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 70,
                            Division = "General Government Programs",
                            Office = "Housing/Treasury/Commerce Division"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 69,
                            Division = "General Government Programs",
                            Office = "Justice Branch"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 67,
                            Division = "General Government Programs",
                            Office = "Transportation/GSA Branch"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 72,
                            Division = "General Government Programs",
                            Office = "Treasury Branch"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 60,
                            Division = "Health Programs",
                            Office = "HHS Branch"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 58,
                            Division = "Health Programs",
                            Office = "Office of the Associate Director, Health Division"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 59,
                            Division = "Health Programs",
                            Office = "Office of the Deputy Associate Director, Health Division"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 64,
                            Division = "Health Programs",
                            Office = "Health Insurance/Data/Analysis Branch"
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 61,
                            Division = "Health Programs",
                            Office = "Medicaid Branch"
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 62,
                            Division = "Health Programs",
                            Office = "Medicare Branch"
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 63,
                            Division = "Health Programs",
                            Office = "Public Health Branch"
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 31,
                            Division = "Information Tech & E-govt U",
                            Office = " "
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 31,
                            Division = "ITOR/Admin Services",
                            Office = ""
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 31,
                            Division = "ITOR/CIO",
                            Office = ""
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 31,
                            Division = "ITOR/E-Gov Cyber Security",
                            Office = ""
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 31,
                            Division = "ITOR/E-Gov DAD",
                            Office = ""
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 31,
                            Division = "ITOR/E-Gov Oversight and Analytics",
                            Office = ""
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 31,
                            Division = "ITOR/E-Gov Policy-Budget-Comms",
                            Office = ""
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 31,
                            Division = "ITOR/General Counsel",
                            Office = ""
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 25,
                            Division = "ITOR/USDS",
                            Office = ""
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 12,
                            Division = "Legislative Reference Division",
                            Office = "Economic/Science/General Government Branch"
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 13,
                            Division = "Legislative Reference Division",
                            Office = "Health/Education/Veterans/Social Program Branch"
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 11,
                            Division = "Legislative Reference Division",
                            Office = ""
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 11,
                            Division = "Legislative Reference Division",
                            Office = "Office of the Assistant Director"
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 14,
                            Division = "Legislative Reference Division",
                            Office = "Resources/Defense/International Branch"
                        },
                        new
                        {
                            Id = 39,
                            DepartmentId = 8,
                            Division = "Management and Operations Division",
                            Office = ""
                        },
                        new
                        {
                            Id = 40,
                            DepartmentId = 8,
                            Division = "Management and Operations Division",
                            Office = "Office of Budget, Finance, and Travel Management"
                        },
                        new
                        {
                            Id = 41,
                            DepartmentId = 8,
                            Division = "Management and Operations Division",
                            Office = "Office of Human Capital"
                        },
                        new
                        {
                            Id = 42,
                            DepartmentId = 8,
                            Division = "Management and Operations Division",
                            Office = "Office of Information Technology"
                        },
                        new
                        {
                            Id = 43,
                            DepartmentId = 8,
                            Division = "Management and Operations Division",
                            Office = "Office of Support Services"
                        },
                        new
                        {
                            Id = 44,
                            DepartmentId = 79,
                            Division = "National Security Programs",
                            Office = "Command/Control/Communications/Intelligence Branch"
                        },
                        new
                        {
                            Id = 45,
                            DepartmentId = 77,
                            Division = "National Security Programs",
                            Office = "Economics Affairs"
                        },
                        new
                        {
                            Id = 46,
                            DepartmentId = 75,
                            Division = "National Security Programs",
                            Office = "International Affairs Division"
                        },
                        new
                        {
                            Id = 47,
                            DepartmentId = 78,
                            Division = "National Security Programs",
                            Office = "National Security Division"
                        },
                        new
                        {
                            Id = 48,
                            DepartmentId = 74,
                            Division = "National Security Programs",
                            Office = "Office of the Associate Director, NSP"
                        },
                        new
                        {
                            Id = 49,
                            DepartmentId = 87,
                            Division = "National Security Programs",
                            Office = "Defense Investments Branch"
                        },
                        new
                        {
                            Id = 50,
                            DepartmentId = 80,
                            Division = "National Security Programs",
                            Office = "Defense Operations, Personnel, and Support Branch"
                        },
                        new
                        {
                            Id = 51,
                            DepartmentId = 76,
                            Division = "National Security Programs",
                            Office = "State Branch"
                        },
                        new
                        {
                            Id = 52,
                            DepartmentId = 82,
                            Division = "National Security Programs",
                            Office = "Veterans Affairs/Defense Health Branch"
                        },
                        new
                        {
                            Id = 53,
                            DepartmentId = 50,
                            Division = "Natural Resource Programs",
                            Office = "Agriculture Branch"
                        },
                        new
                        {
                            Id = 54,
                            DepartmentId = 46,
                            Division = "Natural Resource Programs",
                            Office = "Energy Branch"
                        },
                        new
                        {
                            Id = 55,
                            DepartmentId = 45,
                            Division = "Natural Resource Programs",
                            Office = "Energy/Science/Water Division"
                        },
                        new
                        {
                            Id = 56,
                            DepartmentId = 51,
                            Division = "Natural Resource Programs",
                            Office = "Environment Branch"
                        },
                        new
                        {
                            Id = 57,
                            DepartmentId = 52,
                            Division = "Natural Resource Programs",
                            Office = "Interior Branch"
                        },
                        new
                        {
                            Id = 58,
                            DepartmentId = 44,
                            Division = "Natural Resource Programs",
                            Office = "Office of the Associate Director, NRP"
                        },
                        new
                        {
                            Id = 59,
                            DepartmentId = 49,
                            Division = "Natural Resource Programs",
                            Office = "Natural Resources Division"
                        },
                        new
                        {
                            Id = 60,
                            DepartmentId = 47,
                            Division = "Natural Resource Programs",
                            Office = "Science and Space Branch"
                        },
                        new
                        {
                            Id = 61,
                            DepartmentId = 48,
                            Division = "Natural Resource Programs",
                            Office = "Water and Power Branch"
                        },
                        new
                        {
                            Id = 62,
                            DepartmentId = 17,
                            Division = "Office Assistant Director Budget Review",
                            Office = "Budget Analysis Branch"
                        },
                        new
                        {
                            Id = 63,
                            DepartmentId = 21,
                            Division = "Office Assistant Director Budget Review",
                            Office = "Budget Concept Branch"
                        },
                        new
                        {
                            Id = 64,
                            DepartmentId = 15,
                            Division = "Office Assistant Director Budget Review",
                            Office = ""
                        },
                        new
                        {
                            Id = 65,
                            DepartmentId = 20,
                            Division = "Office Assistant Director Budget Review",
                            Office = "Budget Review Branch"
                        },
                        new
                        {
                            Id = 66,
                            DepartmentId = 18,
                            Division = "Office Assistant Director Budget Review",
                            Office = "Budget Systems Branch"
                        },
                        new
                        {
                            Id = 67,
                            DepartmentId = 28,
                            Division = "Office of Fed Financial Mgmt",
                            Office = "Financial Integrity and Risk Management Branch"
                        },
                        new
                        {
                            Id = 68,
                            DepartmentId = 29,
                            Division = "Office of Fed Financial Mgmt",
                            Office = "Management Controls and Assistance Branch"
                        },
                        new
                        {
                            Id = 69,
                            DepartmentId = 27,
                            Division = "Office of Fed Financial Mgmt",
                            Office = "Office of Deputy Controller"
                        },
                        new
                        {
                            Id = 70,
                            DepartmentId = 89,
                            Division = "Office of Federal Procurement Policy",
                            Office = "Efficiency, Data, and Workforce Management Branch"
                        },
                        new
                        {
                            Id = 71,
                            DepartmentId = 30,
                            Division = "Office of Federal Procurement Policy",
                            Office = "Office of the Administrator, OFPP"
                        },
                        new
                        {
                            Id = 72,
                            DepartmentId = 90,
                            Division = "Office of Federal Procurement Policy",
                            Office = "Policey Development and Innovation Branch"
                        },
                        new
                        {
                            Id = 73,
                            DepartmentId = 9,
                            Division = "Office of General Counsel",
                            Office = ""
                        },
                        new
                        {
                            Id = 74,
                            DepartmentId = 36,
                            Division = "Office Of Information And Regulatory Affairs",
                            Office = "OIRA/ODA/Food, Health, and Labor Branch"
                        },
                        new
                        {
                            Id = 75,
                            DepartmentId = 37,
                            Division = "Office of Information and Regulatory Affairs",
                            Office = "OIRA/ODA/Information Policy Branch"
                        },
                        new
                        {
                            Id = 76,
                            DepartmentId = 37,
                            Division = "Office of Information and Regulatory Affairs",
                            Office = "OIRA/ODA/Information Policy Branch O Fund"
                        },
                        new
                        {
                            Id = 77,
                            DepartmentId = 38,
                            Division = "Office of Information and Regulatory Affairs",
                            Office = "OIRA/ODA/Natural Resources and Environmental Branch"
                        },
                        new
                        {
                            Id = 78,
                            DepartmentId = 35,
                            Division = "Office of Information and Regulatory Affairs",
                            Office = ""
                        },
                        new
                        {
                            Id = 79,
                            DepartmentId = 35,
                            Division = "Office Of Information And Regulatory Affairs",
                            Office = "Office of the Administrator, OIRA"
                        },
                        new
                        {
                            Id = 80,
                            DepartmentId = 35,
                            Division = "Office of Information and Regulatory Affairs",
                            Office = "Office of the Deputy Administrator"
                        },
                        new
                        {
                            Id = 81,
                            DepartmentId = 39,
                            Division = "Office of Information and Regulatory Affairs",
                            Office = "OIRA/ODA/Privacy Branch"
                        },
                        new
                        {
                            Id = 82,
                            DepartmentId = 40,
                            Division = "Office of Information and Regulatory Affairs",
                            Office = "OIRA/ODA/Statistical and Science Policy Branch"
                        },
                        new
                        {
                            Id = 83,
                            DepartmentId = 41,
                            Division = "Office of Information and Regulatory Affairs",
                            Office = "OIRA/ODA/Transportation and Security Branch"
                        },
                        new
                        {
                            Id = 84,
                            DepartmentId = 41,
                            Division = "Office of Information and Regulatory Affairs",
                            Office = "OIRA/ODA/Transportation and Security Branch O Fund"
                        },
                        new
                        {
                            Id = 85,
                            DepartmentId = 30,
                            Division = "Office of Scheduling and Advance",
                            Office = "Office of the Administrator, OFPP"
                        },
                        new
                        {
                            Id = 86,
                            DepartmentId = 10,
                            Division = "Staff Offices",
                            Office = "Economic Policy"
                        },
                        new
                        {
                            Id = 87,
                            DepartmentId = 9,
                            Division = "Staff Offices",
                            Office = "General Counsel"
                        },
                        new
                        {
                            Id = 88,
                            DepartmentId = 6,
                            Division = "Staff Offices",
                            Office = "Legislative Affairs"
                        },
                        new
                        {
                            Id = 89,
                            DepartmentId = 8,
                            Division = "Staff Offices",
                            Office = "Management and Operations Division"
                        },
                        new
                        {
                            Id = 90,
                            DepartmentId = 22,
                            Division = "Staff Offices",
                            Office = "Performance and Personnel Management Division"
                        },
                        new
                        {
                            Id = 91,
                            DepartmentId = 1,
                            Division = "Staff Offices",
                            Office = "Communications"
                        });
                });

            modelBuilder.Entity("Mod.Framework.User.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ein")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("GivenName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("InactiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MailNickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerEin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Office")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficePhone")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("PreferredName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportsToEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("SamAccountName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Upn")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ReportsToEmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Mod.Framework.User.Entities.EmployeeAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attribute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeAttribute");
                });

            modelBuilder.Entity("Mod.Framework.User.Entities.EmployeeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeGroup");
                });

            modelBuilder.Entity("Mod.Framework.User.Entities.Department", b =>
                {
                    b.HasOne("Mod.Framework.User.Entities.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Mod.Framework.User.Entities.DepartmentMap", b =>
                {
                    b.HasOne("Mod.Framework.User.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mod.Framework.User.Entities.Employee", b =>
                {
                    b.HasOne("Mod.Framework.User.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Mod.Framework.User.Entities.Employee", "ReportsTo")
                        .WithMany("DirectReports")
                        .HasForeignKey("ReportsToEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Mod.Framework.User.Entities.EmployeeAttribute", b =>
                {
                    b.HasOne("Mod.Framework.User.Entities.Employee", "Employee")
                        .WithMany("EmployeeAttributes")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mod.Framework.User.Entities.EmployeeGroup", b =>
                {
                    b.HasOne("Mod.Framework.User.Entities.Employee", "Employee")
                        .WithMany("Groups")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
